import React from 'react';
import { Info, ExternalLink, ShieldCheck, Database, Cpu, Compass, BookOpen } from 'lucide-react';

export const AboutSourcesView: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-16 animate-fadeIn">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-black text-white tracking-tight flex items-center gap-2">
          <BookOpen className="w-6 h-6 text-teal-400" />
          Transparency, Data Sources & Model Methodology
        </h2>
        <p className="text-xs text-slate-400 mt-1">
          AirAware is built on the principle of complete transparency regarding environmental modeling vs statutory sensor measurements.
        </p>
      </div>

      {/* Model vs Ground Measurement Explainer */}
      <div className="p-6 rounded-3xl bg-slate-900 border border-teal-500/30 space-y-3">
        <div className="flex items-center gap-2 text-teal-400">
          <ShieldCheck className="w-5 h-5" />
          <h3 className="text-sm font-bold uppercase tracking-wider text-white">
            Atmospheric Modeling vs Statutory Ground Sensors
          </h3>
        </div>
        <p className="text-xs text-slate-300 leading-relaxed">
          AirAware uses data from <strong>Open-Meteo Air Quality</strong>, which integrates numerical chemical transport models from the <strong>Copernicus Atmosphere Monitoring Service (CAMS)</strong> and the <strong>Finnish Meteorological Institute (SILAM)</strong>.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2 text-xs">
          <div className="p-3.5 rounded-2xl bg-slate-950 border border-slate-800">
            <strong className="text-teal-300 block mb-1">Atmospheric Chemistry Models (AirAware)</strong>
            <p className="text-slate-400 leading-relaxed text-[11px]">
              Combines satellite optical depth retrievals, numerical emissions inventories, and boundary layer thermodynamics to generate continuous, unbroken spatial grids across every coordinate globally.
            </p>
          </div>
          <div className="p-3.5 rounded-2xl bg-slate-950 border border-slate-800">
            <strong className="text-amber-300 block mb-1">Regulatory Ground Stations (e.g. CPCB)</strong>
            <p className="text-slate-400 leading-relaxed text-[11px]">
              Physical beta-attenuation or gravimetric monitors located at fixed geographic sites. While highly accurate at their exact pin, they have limited spatial coverage outside major urban centres.
            </p>
          </div>
        </div>
      </div>

      {/* Active Data Providers Grid */}
      <div className="space-y-4">
        <h3 className="text-base font-bold text-white flex items-center gap-2">
          <Database className="w-4 h-4 text-teal-400" />
          Integrated Providers & Specifications
        </h3>

        <div className="space-y-3">
          {[
            {
              title: 'Open-Meteo Air Quality API',
              url: 'https://air-quality-api.open-meteo.com',
              type: 'Chemical Transport & Aerosol Forecast Model',
              specs: 'PM2.5, PM10, European AQI, US AQI, NO2, O3, CO, SO2, UV Index, Aerosol Dust',
              description: 'Provides 2-day hourly forecasts and current surface layer concentrations generated by the European Copernicus Earth observation programme.'
            },
            {
              title: 'Open-Meteo Global Weather Prediction API',
              url: 'https://open-meteo.com',
              type: 'Numerical Weather Prediction (NWP)',
              specs: 'Temperature, Relative Humidity, Wind Speed/Direction, Precipitation, Weather Code (WMO), Surface Pressure',
              description: 'Grounded in ECMWF IFS (European Centre for Medium-Range Weather Forecasts) and NOAA GFS global models.'
            },
            {
              title: 'Open-Meteo Geocoding Gazeteer',
              url: 'https://geocoding-api.open-meteo.com',
              type: 'Global Gazeteer & Reverse Lookup',
              specs: 'City names, administrative divisions, coordinates, population, timezone',
              description: 'Open-source gazetteer derived from OpenStreetMap and GeoNames.'
            },
            {
              title: 'India Meteorological Department (IMD) / NDMA Bulletins',
              url: 'https://mausam.imd.gov.in',
              type: 'Official National Hydrometeorological & Disaster Bulletins',
              specs: 'Severe heatwave alerts, cyclonic depressions, storm surge watches, flood advisories',
              description: 'Official national early warning bulletins distinguishing government decrees from model forecasts.'
            },
            {
              title: 'Google Gemini 3.8 Flash SDK (@google/genai)',
              url: 'https://ai.google.dev',
              type: 'Multimodal Environmental Reasoning AI',
              specs: 'Model: gemini-3.8-flash, structured context grounding, system prompts for public health resilience',
              description: 'Translates complex atmospheric chemistry and meteorological vectors into simple, actionable daily advice.'
            }
          ].map(source => (
            <div key={source.title} className="p-5 rounded-2xl bg-slate-900 border border-slate-800">
              <div className="flex items-center justify-between">
                <h4 className="text-sm font-bold text-white">{source.title}</h4>
                <a
                  href={source.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-xs text-teal-400 hover:text-teal-300 flex items-center gap-1 font-medium"
                >
                  Provider Docs <ExternalLink className="w-3 h-3" />
                </a>
              </div>
              <div className="text-[11px] font-mono text-teal-300 mt-0.5">{source.type}</div>
              <p className="text-xs text-slate-300 mt-2 leading-relaxed">{source.description}</p>
              <div className="mt-2 text-[11px] text-slate-400">
                <span className="font-semibold text-slate-300">Variables:</span> {source.specs}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Hackathon Track 2 Mission Statement */}
      <div className="p-6 rounded-3xl bg-slate-900/60 border border-slate-800 text-xs text-slate-400 space-y-2">
        <h4 className="text-sm font-bold text-white">Hack2Skill Track 2: Clean Air & Climate Resilience</h4>
        <p className="leading-relaxed">
          AirAware addresses both halves of the climate crisis: enabling citizens to reduce personal pollution exposure on smog days while building proactive community resilience against extreme weather emergencies like heatwaves, cyclones, and urban flooding.
        </p>
      </div>
    </div>
  );
};
